"""made changes

Revision ID: 34fecb100c25
Revises: 4f17f34e3a6c
Create Date: 2018-08-17 19:27:42.280155

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34fecb100c25'
down_revision = '4f17f34e3a6c'
branch_labels = ()
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ingredient')
    op.drop_table('direction')
    op.add_column('recipe', sa.Column('directions', sa.Text(), nullable=True))
    op.add_column('recipe', sa.Column('ingredients', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipe', 'ingredients')
    op.drop_column('recipe', 'directions')
    op.create_table('direction',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('date_posted', sa.DATETIME(), nullable=False),
    sa.Column('recpie_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['recpie_id'], ['recipe.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ingredient',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('content', sa.VARCHAR(length=50), nullable=False),
    sa.Column('date_posted', sa.DATETIME(), nullable=False),
    sa.Column('recpie_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['recpie_id'], ['recipe.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
