"""made changes

Revision ID: 4e76ba92b35d
Revises: 59abf2e59fa0
Create Date: 2018-08-16 09:53:36.120288

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e76ba92b35d'
down_revision = '59abf2e59fa0'
branch_labels = ()
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe', sa.Column('servings', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipe', 'servings')
    # ### end Alembic commands ###
