"""made changes

Revision ID: 59abf2e59fa0
Revises: 847c35ec3247
Create Date: 2018-08-16 09:27:37.724719

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59abf2e59fa0'
down_revision = '847c35ec3247'
branch_labels = ()
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe', sa.Column('cook_time', sa.String(length=4), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipe', 'cook_time')
    # ### end Alembic commands ###
