"""first migration

Revision ID: 847c35ec3247
Revises: 
Create Date: 2018-08-14 10:43:31.895104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '847c35ec3247'
down_revision = None
branch_labels = ('default',)
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
