"""made changes

Revision ID: a6999bffe123
Revises: 34fecb100c25
Create Date: 2018-08-20 17:24:01.303961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6999bffe123'
down_revision = '34fecb100c25'
branch_labels = ()
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
    	'user',
    	'image_file',
    	existing_type=sa.String(20),
    	type_=sa.String(100)
	)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
    	'user',
    	'image_file',
    	existing_type=sa.String(100),
    	type_=sa.String(20)
	)
    # ### end Alembic commands ###
