"""empty message

Revision ID: b89a187e6255
Revises: 91c7a2e15f30
Create Date: 2018-08-24 07:56:48.559311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b89a187e6255'
down_revision = '91c7a2e15f30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('table_i_will_delete',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('table_i_will_delete')
    # ### end Alembic commands ###
